name: Merge dev to main

on:
  schedule:
    - cron: '30 14 * * *'  # 23:30 JST は 14:30 UTC
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  Workflow_:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
          with: main
      
      - name: ls
        run: ls -a

      - name: branch
        run: git branch -a
  merge:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4

    - name: Checkout main branch
      run: git checkout main
    
    - name: Merge dev into main
      run: git merge dev

    - name: Push changes to main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push origin main