name: Merge dev to main

on:
  schedule:
    - cron: '30 14 * * *'  # 23:30 JST は 14:30 UTC
  push:
    branches:
      - dev
  workflow_dispatch:
permissions:
  contents: write
jobs:
  Workflow_:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: ls
        run: ls -a

      - name: branch
        run: git branch -a
  merge:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone Repo
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Set up conf
      run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

    - name: Checkout dev branch
      run: git checkout main
    
    - name: Checkout main branch
      run: git checkout main
    
    - name: Merge dev into main
      run: git merge dev

    - name: Push changes to main
      run: git push origin main